name: Terraform - Observability Core (Dev)

on:
  push:
    branches:
      - dev
    paths:
      - services/observability-core/**
      - modules/**

permissions:
  id-token: write
  contents: read

env:
  ARM_USE_OIDC: true
  ARM_CLIENT_ID: ${{ secrets.SHARED_SERVICES_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  terraform:
    environment: baseline-dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: |
          terraform -chdir=services/observability-core init \
            -backend-config=backend.dev.hcl \
            -reconfigure

      - name: Terraform Plan
        run: |
          terraform -chdir=services/observability-core plan \
            -var-file=env/dev.tfvars

      # - name: Terraform Apply
      #   run: |
      #     terraform -chdir=services/observability-core apply \
      #       -var-file=env/dev.tfvars -auto-approve
