name: Terraform - Backend State Provisioning (Dev)

on:
  push:
    branches:
      - dev
    paths:
      - services/shared-services/sharedstate/backend-state-provisioning/**
      - modules/**
      - .github/workflows/terraform-backendstateprov.yml

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ARM_USE_OIDC: true
  ARM_USE_AZUREAD: true
  ARM_CLIENT_ID: ${{ secrets.SHARED_SERVICES_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  terraform:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: |
          terraform -chdir=services/shared-services/sharedstate/backend-state-provisioning init \
            -backend-config=backend.dev.hcl \
            -reconfigure

      - name: Terraform Plan
        id: plan
        run: |
          terraform -chdir=services/shared-services/sharedstate/backend-state-provisioning plan \
            -var-file=../env/dev/backend-state-provisioning-dev.tfvars \
            # -out=tfplan

      - name: Terraform Apply
        run: |
          terraform -chdir=services/shared-services/sharedstate/backend-state-provisioning apply \
            -var-file=../env/dev/backend-state-provisioning-dev.tfvars -auto-approve
