name: Terraform - Shared Services (Dev)

on:
  push:
    branches:
      - dev
    paths:
      - services/shared-services/sharedstate/**
      - modules/**
      - .github/workflows/terraform-sharedstate.yml

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ARM_USE_OIDC: true
  ARM_CLIENT_ID: ${{ secrets.SHARED_SERVICES_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  terraform:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: |
          terraform -chdir=services/shared-services/sharedstate/core-shared-state init \
            -backend-config=backend.dev.hcl \
            -reconfigure

      - name: Terraform Plan
        id: plan
        run: |
          terraform -chdir=services/shared-services/sharedstate/core-shared-state plan \
            -var-file=../env/dev/core-dev.tfvars \
            # -out=tfplan
          
          #Show the full plan to make attributes visible
          # terraform -chdir=services/shared-services/sharedstate/core-shared-state show -json tfplan

          # echo "--- DETAILED ATTRIBUTE COMPARISON ---"
          # terraform -chdir=services/shared-services/sharedstate/core-shared-state show -json tfplan | jq '
          #   .resource_changes[] | 
          #   select(.address == "module.tfstate_storage.azurerm_storage_account.this") | 
          #   {
          #     resource: .address,
          #     before: {
          #       shared_access_key_enabled: .change.before.shared_access_key_enabled,
          #       public_network_access: .change.before.public_network_access_enabled
          #     },
          #     after: {
          #       shared_access_key_enabled: .change.after.shared_access_key_enabled,
          #       public_network_access: .change.after.public_network_access_enabled
          #     }
          #   }'
          # echo "------------------------------------"

      - name: Terraform Apply
        run: |
          terraform -chdir=services/shared-services/core-shared-state apply \
            -var-file=../env/core-dev.tfvars -auto-approve
